### ISSUE TITLE
bypass as Dictionary vs boolean?

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/themes#1]
Is there a reason for making the bypass state a dictionary:

`bypass = {"state": False}`

instead of just using a boolean variable directly?

`bypass = False`

Also, what does bypass refer to?  maybe provide a longer variable name that's more descriptive so the code is easier to read?

**Comment by punctuations** [comment]
because it won't let me mutate the value if it is outside of the function, so to get around that I used dictionary, is there a better way to do this?

**Comment by tylerecouture** [comment]
Can you post the code and stacktrace here?

**Comment by punctuations** [comment]
@tylerecouture what do you mean by stacktrace

**Comment by tylerecouture** [comment]
It's the stack of errors that get output to the console.  I think it's
actually called "Traceback" in python:
https://realpython.com/python-traceback/

**Comment by punctuations** [comment]
solved by using a time-based system, spamblock is a dict with `{"time": DEFAULT_SPAMBLOCK, "waiting": False}`

**Comment by punctuations** [comment]
waiting meaning waiting for input

**Comment by tylerecouture** [comment]
I don't understand why this is a dict at all. Maybe you are too immersed in
json, lol
