### ISSUE TITLE
Set spamblock time

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/themes#3]
The current player allows me to set the spam block time with the secret code.  

I enter the secret code, then it prompts for the new spam block time.

To turn it off I enter 0, to set it to 30 minutes I enter 30, etc.

**Comment by punctuations** [comment]
so instead of a toggle, you want a prompt for the amount of minutes?

**Comment by tylerecouture** [comment]
Yes, that's what we currently have.  Having both options would be cool too!

**Comment by punctuations** [comment]
I just used the time-based system :+1:
