### ISSUE TITLE
Run script

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/themes#4]
I think it would be good to have the run script in this repo.  The bash script should:

- [x] Set the volume on the pi (if needed)
- [x] git pull
- [x] pip install -r requirements.txt
- [x] run player.py 
- [x] works in production

**Comment by tylerecouture** [comment]
Doesn't work!

**Comment by punctuations** [comment]
what was printed out? -- or what was the failure?

**Comment by tylerecouture** [comment]
The theme player doesn't play songs... does it?

**Comment by tylerecouture** [comment]
On the pi I mean
