### ISSUE TITLE
rename script and add __main__ method

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/themes#7]
Some tweaks:

- [x] rename the python script "themes.py"
- [x] create a proper __main__ method: https://realpython.com/python-main-function/
- [x] create a requirements.txt file

**Comment by punctuations** [comment]
what do you want in the requirements.txt file?

**Comment by tylerecouture** [comment]
all the package requirements.
Usually you just do: `pip freeze > requirements.txt` but that would suck if you using the global python install (though try it anyway to see what you get)
Instead, you can just manually list the pip packages that are needed.
Look up `pip freeze` and requirements.txt, they are standard for python projects.

**Comment by tylerecouture** [comment]
https://pip.pypa.io/en/stable/cli/pip_freeze/
